# Generated by Django 5.2.7 on 2025-12-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_options_alter_activity_activity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('RUN', 'Running'), ('CYC', 'Cycling'), ('SWM', 'Swimming'), ('GYM', 'Gym'), ('YOG', 'Yoga'), ('OTH', 'Other')], default='OTH', max_length=10),
        ),
        migrations.AlterField(
            model_name='activity',
            name='calories_burned',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
