# Generated by Django 5.2.7 on 2025-12-17 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_distance_km_activity_notes_and_more'),
        ('activities', '0004_add_avatar_to_user'),
    ]

    operations = [
    ]
